-- Provinces and cities for venue location (Philippines PSGC)
-- Seed data in seed-psgc.sql (generated by npm run generate:psgc-seed)

CREATE TABLE IF NOT EXISTS public.provinces (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  code text
);

CREATE TABLE IF NOT EXISTS public.cities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  province_id uuid NOT NULL REFERENCES public.provinces(id) ON DELETE CASCADE,
  name text NOT NULL,
  code text
);

CREATE INDEX IF NOT EXISTS idx_cities_province ON public.cities(province_id);

-- Add province_id and city_id to venues; drop address
ALTER TABLE public.venues
  ADD COLUMN IF NOT EXISTS province_id uuid REFERENCES public.provinces(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS city_id uuid REFERENCES public.cities(id) ON DELETE SET NULL;

-- Drop address (existing venues will have null province_id/city_id until edited)
ALTER TABLE public.venues DROP COLUMN IF EXISTS address;

-- RLS: geography tables are reference data, public read
ALTER TABLE public.provinces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read provinces" ON public.provinces
  FOR SELECT USING (true);

CREATE POLICY "Public can read cities" ON public.cities
  FOR SELECT USING (true);
